# Generated by Django 3.1.3 on 2020-11-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('period', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('autor', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('category', models.CharField(choices=[('HI', 'Histoire'), ('SC', 'Science'), ('RE', 'Religion'), ('SP', 'Sport'), ('LI', 'Littérature'), ('PH', 'Philosophie')], default='HI', max_length=2)),
                ('theme', models.CharField(max_length=200)),
                ('wiki', models.URLField()),
            ],
        ),
    ]
