# Generated by Django 3.1.3 on 2020-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20201117_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='period',
            field=models.IntegerField(choices=[(1, 'Préhistoire'), (2, 'Première antiquité'), (3, 'VIème siècle av-jc'), (4, 'Vème siècle av-jc'), (5, 'IVème siècle av-jc'), (6, 'IIIème siècle av-jc'), (7, 'IIème siècle av-jc'), (8, 'Ier siècle av-jc'), (9, 'Ier siècle'), (10, 'IIème siècle'), (11, 'IIIème siècle'), (12, 'IVème siècle'), (13, 'Vème siècle'), (14, 'VIème siècle'), (15, 'VIIème siècle'), (16, 'VIIIème siècle'), (17, 'IXème siècle'), (18, 'Xème siècle'), (19, 'XIème siècle'), (20, 'XIIème siècle'), (21, 'XIIIème siècle'), (22, 'XIVème siècle'), (23, 'XVème siècle'), (24, 'XVIème siècle'), (25, 'XVIIème siècle'), (26, 'XVIIIème siècle'), (27, 'XIXème siècle'), (28, 'XXème siècle'), (29, 'XXIème siècle')]),
        ),
    ]
